### ISSUE TITLE
Node can't handle multiple locations (when getting a route)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1855] opened 2018-06-01 16:06 UTC
Was debugging on @sigpie 's machine a sec ago on, i think, the `feat__location-route-picker`-branch. When creating a need with a route, i.e. a fromLocation and toLocation (and if you feel fancy another extra location via the location-picker) the jsonld already gets build properly and send via the websocket. However, when the client fetches the need again a second later (i guess, to also get the crypto?) all bounding-boxes are grouped into the same two blank-nodes that have 2-3 longitudes respectively latitudes, same if you click on the show-rdf link and look at the trig on the node. Seems that the location-handling on the node contains a bug where it assumes that there's only one location / one occurrence of the predicates _within_ the location structure. Fix: it needs to distinguish `won:hasLocation`, `won:hasToLocation` and `won:hasFromLocation`.

**Comment by quasarchimaere** [comment] 2018-06-01 17:02
we should not use won:hasToLocation and won:hasFromLocation to begin with, we should use the structure of s:TravelAction (as shown in the taxi goal examples @sigpie knows where they are), that way we do not have to change the taxibot shacl constraints and we wont include a (nonsensical) boundingbox for the two points given within the travelaction, maybe that already fixes our problem

**Comment by fkleedorfer** [comment] 2018-06-01 17:34
Please post the jsonld that is SENT by the owner webapp and the TTL retrieved directly from the WoN node (not via the linkeddata bridge)?

**Comment by fkleedorfer** [comment] 2018-06-01 17:38
@quasarchimaere I understand the concerns. It's true that we already thought we knew what data we wanted out of that detail. However, when you actually design it, you see that it does not make so much sense to show two maps for a route, one for the start and one for the destination. Having said that, it should be possible to keep the data structure the way it was intended - we can just put the two locations into one map. Right, @sigpie ?

**Comment by quasarchimaere** [comment] 2018-06-01 18:05
@fkleedorfer i know it doesnt make much sense to show two maps, i discussed this with @sigpie (one map with two markers suffices) however my concern didnt lie in the presentation of the ui, itwas in the rdf outcome which we spoke about in detail, and i just wanted to mention that the boundingbox will not and does not make sense in a route so why do we not just drop it if it is causing problems?

**Comment by fkleedorfer** [comment] 2018-06-01 18:13
I tried and failed to say exactly that

**Comment by fkleedorfer** [comment] 2018-06-01 18:14
But that won't fix the problem.

**Comment by sigpie** [comment] 2018-06-03 08:27
The bounding boxes can be removed, they are currently only used to correctly zoom in on selected locations when adding a route. I'll also fix my branch to better match the intended data structure.

**Comment by fkleedorfer** [comment] 2018-06-08 14:46
This seems fixed now, right, @sigpie ?

**Comment by sigpie** [comment] 2018-06-08 17:38
The issue does not occur with the current route and location picker implementations. If we decide to change how location information is handled and the problem reappears, this issue can be reopened.

**Closed by sigpie** 2018-06-08 17:38 UTC
Labels: testing
