### ISSUE TITLE
Access to full post information in matches view.

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1184] opened 2017-08-23 10:04 UTC
Atm there's no way to get to the post-info page of other people's needs from the matches view, which means that their picked location isn't visible. We could link it, or even better, make sure the popup contains all of the post information (e.g. a map).

**Comment by quasarchimaere** [comment] 2017-10-11 07:18
duplicate of #765 -> close

**Closed by quasarchimaere** 2017-10-11 07:18 UTC
