### ISSUE TITLE
Type Error: c.get is not a function when posting a need

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#964] opened 2017-02-02 11:39 UTC
Message: `TypeError: c.get is not a function`

culprit:
```
/**
     * Add's the connectionUri to the needs connections. Makes
     * sure the same uri doesn't get added twice.
     * NOTE: As this function goes through all previous connections
     * to make sure that there are no duplicates, avoid using it
     * when adding a bunch of connections at once.
     * @param state
     * @param needUri
     * @param connectionUri
     * @return {*}
     */
    function addConnection(state, needUri, connectionUri) {
        var pathToConnections = ['ownNeeds', needUri, 'won:hasConnections', 'rdfs:member'];
        if (!state.getIn(pathToConnections)) {
            //make sure the rdfs:member array exists
            state = state.setIn(pathToConnections, Immutable.List());
        }
        var connections = state.getIn(pathToConnections);
        if (connections.filter(function (c) {
            return c.get('@id') === connectionUri;
        }).size > 0) {
            // connection's already been added to the need before
            return state;
        } else {
            // new connection, add it to the need
            return state.updateIn(pathToConnections, function (connections) {
                return connections.push(Immutable.fromJS({ '@id': connectionUri }));
            });
        }
    }

```

**Comment by quasarchimaere** [comment] 2017-02-02 12:54
should be a duplicate of something that has already been fixed (please retest on master)

**Comment by m0ru** [comment] 2017-03-20 17:49
Posting works fine (commit b2481ae)

**Closed** 2017-03-20 17:50 UTC
Labels: testing
