### ISSUE TITLE
Skills - "#couch #free" (inherited placeholder)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2161] opened 2018-07-17 15:49 UTC
![image](https://user-images.githubusercontent.com/1730492/42829273-bfdb3bc6-89e9-11e8-97f9-e2601f33617b.png)

**Comment by m0ru** [comment] 2018-07-17 15:52
There's a few other components as well with unlucky values / spooky action at a distance. we might want to abstain from using the spread-operator to transfer defaults. 

We might want to include a dev-time assert that checks for complete use-case-definitions however (or switch to a typed language at last ;p ^^ )

**Comment by quasarchimaere** [comment] 2018-07-17 16:51
i implemented the placeholders solely for the initial detail-definitions, if there is a need for change in specifics please adapt accordingly, i think the spread operator works as intended here and we should not use any other failsafe for non abstract details, afaik the safe guards in the abstract details suffice (e.g. the functions that throw the errors in the detail-definitions.js)...however if there is a need for certain default vars within the pickers and viewers besides the placeholder please create specific issues for each of these cases (e.g if one would want to define configurable stepping or min max values in the numberpicker or date/time pickers, or if one wants to be really fancy locationbased limitations and such)

**Comment by m0ru** [comment] 2018-07-18 11:47
what i mean, is that we should avoid invisibly/implicitely copying stuff, as it might lead to wierd config value if whoever creates a component doesn't properly check everything. if it's explicit (and missing values checked) it's hard to accidentally misconfigure them ^^"

**Comment by quasarchimaere** [comment] 2018-07-18 13:07
abstractDetails do exactly that

**Comment by peacememories** [comment] 2018-07-18 14:47
Also, our current safeguards for abstract details essentially throw errors when they are called, instead of when the usecase is constructed.
I suggest making details available as functions that take overrides. This way overrides can still be supplied, and abstract details can check on creation if all necessary data is present.

**Comment by quasarchimaere** [comment] 2018-07-19 10:52
skills detail has a good placeholder now, closing this issue

**Closed by quasarchimaere** 2018-07-19 10:52 UTC
Labels: ready
