### ISSUE TITLE
Non-Text-Dependant Placeholder Pics

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1720] opened 2018-05-08 19:27 UTC
## Motivation 

As our plan is to allow arbitrary RDF in needs, there's no guarantee that there'll be a `dc:title` or even text at all in the need. Thus our current method of using the initial letter won't work in the long-term. Even in the short-term, the method produces visually similar results for quick-reply-needs, that all share the same title and are displayed next to each other. 

### References

1. Harvey, Michelle Venetucci. “Design Avatars That Make Sense — and Be More Inclusive in the Process.” UX Collective, May 2, 2017. <https://uxdesign.cc/design-avatars-that-make-sense-and-be-more-inclusive-in-the-process-d4dd6a486ea6>.
2. “Avatars, Identicons, and Hash Visualization.” Jussi Judin’s weblog, February 4, 2018. <https://barro.github.io/2018/02/avatars-identicons-and-hash-visualization/>.

### Discussion

* **first letters:** see motivation. we could theoretically use the first letter of the hash, however the capitalization is usually used with the first letter of any preceding text, i.e. it would break with the common usage of this typographical element.
* Michelle Harvey (see 1, above) argues that **identicons** (e.g. used by github) communicate technicality, crypto and privacy-awareness but also motivate people to add their own images (as they're better looking and more personal). might be very github-associated -- let's make sure that our's look noticeably different. there's a variety of libs for generating identicons:
  * <https://github.com/download13/blockies> (slightly more px than gh, configurable color(!), retro-game-y?, last updated 3y ago, [demo](https://download13.github.io/blockies/))
  * <https://www.npmjs.com/package/identicon.js> (simple unicolor gh-style, js->png/svg, super simple, last update 2m ago, [demo](https://www.npmjs.com/package/identicon.js))
  * <https://www.npmjs.com/package/angularjs-identicon> (angularjs-wrapper for identicon.js (see above), last updated 3m ago)
  * <https://www.npmjs.com/package/jdenticon> (remotely wordpress-style but different enough, using js+canvas, last update 23d ago, [demo](https://jdenticon.com/))
  * <https://www.npmjs.com/package/@unique-violation/identicon.js> (exactly same as gh, js->b64-pngs, last updated 3y ago)
  * <https://www.npmjs.com/package/identicon-github> (gh-style, last update 3y ago)
  * <https://www.npmjs.com/package/ethereum-blockies-base64> (ethereum-styled(?), js->b64-pngs, last updated 2m ago, [demo](https://mycryptohq.github.io/ethereum-blockies-base64/), imo relatively noisy and badly color-schemed)
  * <https://www.npmjs.com/package/identicon> (wordpress-style, requires processing on server)
* **brand-related colors** (think "slack"): less techy but otherwise comparable in properties to the identicons. Slack uses zoom and rotation on the logo. i couldn't find any good libs for this effect, meaning we'd have to develop something for this effect. if we'd go that route, a benefit would be, that it'd be uniquly "WoN".
* **animals, smiley faces, monsters** (e.g. wordpress monsterid), **aliens or pop-culture-figures** probably also won't work, as posts aren't persons/entitities per se. also there might be some unfortunate combinations between post-content and image / some animals might be seen as insults in some contexts.
* **brand-mascots** (e.g. snapchat) we don't have mascots and there's only so many possibilities to use the "W"-logo ^^

### Conclusion

=> blockies or identicon.js. 

blockies look less like github, more game-y. they're not maintained but shouldn't change anyway. identicon.js looks more like github and is actively maintained.

**Comment by m0ru** [comment] 2018-05-09 15:00
Use the need-uris as input for the identicon-functions. This way the need-content can change in the future, but the placeholder-pics stay the same (~github with usernames)

**Comment by m0ru** [comment] 2018-05-09 15:00
The square-image-component needs to be changed for this.

**Comment by m0ru** [comment] 2018-05-18 14:04
## Conclusion @ Avatar Generators (updt.)
we'll use identicon.js as it generates simpler / less noisy identicons.

**Comment by quasarchimaere** [comment] 2018-05-23 19:57
i agree especially with identicons [1] looks pretty similar to the post icon. (2) would make the most sense to me as the own post icon could be in the background (3) would probably look weird on long lists and mobile phones and have too much whitespace in an already scarce space.(4) is something we already tried and it left too much space between posts when they where collapsed, if the gap was only present once the post connections where expanded then the difference was merely visible

**Comment by m0ru** [comment] 2018-05-25 10:56
I've changed the title-pic-split to vertical, as suggested by @quasarchimaere. However, it's still hard to distinguish these / recognize the other post as its own thing[1]. We could go for something like github does with multi-person commits/reviewed commits[2]. Or we might try different variants of visually separating the bocks of ownNeed+connections (it would lose the "connection between two posts" symbolism tho).

Styles for differentiating connections from own posts:

[1]:
![one half of each title picture split vertically](https://user-images.githubusercontent.com/1730492/40442717-bb0181be-5ec4-11e8-9607-7d1db62650f8.png)

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

[2]:
![second card behind the other one](https://user-images.githubusercontent.com/1730492/40443569-083e228c-5ec7-11e8-82b9-59ecb91391be.png)

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

[3]:
![intented cards](https://user-images.githubusercontent.com/1730492/40443211-e6f7a504-5ec5-11e8-9573-8579af3b136f.png)

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

[4]:
![margin between own needs](https://user-images.githubusercontent.com/1730492/40443340-4e6619dc-5ec6-11e8-8747-c1c4acff39da.png)

**Comment by quasarchimaere** [comment] 2018-05-25 11:32
isn't the last comment a duplicate of some sorts?

**Comment by fkleedorfer** [comment] 2018-05-25 14:04
I am very much in favor of indentation! I know we lose precious space, but it adds so much visual structure...

**Comment by m0ru** [comment] 2018-05-25 16:59
more variants:
![image](https://user-images.githubusercontent.com/1730492/40556655-bcead392-604d-11e8-812b-e8fc2f6dff4f.png)

**Comment by m0ru** [comment] 2018-05-25 17:09
another variant: transparent backgrounds

![image](https://user-images.githubusercontent.com/1730492/40557063-32bfd580-604f-11e8-8af2-418267131371.png)

**Comment by m0ru** [comment] 2018-05-25 17:11
tried the small-arrow-thing with the b&w-identicons:
![image](https://user-images.githubusercontent.com/1730492/40557137-749193b8-604f-11e8-8894-f8a75b94bf58.png)

**Comment by quasarchimaere** [comment] 2018-05-25 17:14
first row, second picture is my favourite, color seems to be better than monochrome or transparent, if anything i would make the "own" part a bit bigger (like the first picture in the second row)

**Comment by fkleedorfer** [comment] 2018-05-25 17:34
My fav: row 2 pic 2
Reasons: 
* Conns not so noisy
* Like that the own icon has the matching form. Suggestion, when collapsed, show full own icon and animate the change
* Colors are better.
* The clipped form in that variant has minimal noise with maximum visible icon area

**Comment by fkleedorfer** [comment] 2018-05-25 17:41
Also, we'll probably have to add avatars to that picture The low-noise approach here is positive in that respect, too

**Comment by quasarchimaere** [comment] 2018-05-25 19:21
i agree after reviewing the fav of @fkleedorfer i saw the own post change as well and it makes alot of sense that way

**Comment by m0ru** [comment] 2018-05-30 13:47
three more with crops on the cards instead: 

![image](https://user-images.githubusercontent.com/1730492/40724129-9fadca06-6420-11e8-8da0-38ffb252a509.png)

all of these have the advantage, that they don't crop into the image. the first is lightest, second might be a bit too visually heavy, third is very material design (that would be the first gradient/drop-shadow we have in the application afaik, thus it would break somewhat with our CI)

**Comment by maxstolze** [comment] 2018-05-30 13:55
My favourite is number 3 with the shadows.
If not, 1 is keeping the current design, 2 is to "heavy".

**Comment by quasarchimaere** [comment] 2018-05-30 13:59
i like number 3 the most too from that batch of options, the only issue i would like to address is that i dont think this option translates well in the header if it is displayed when a connection is open.

**Comment by m0ru** [comment] 2018-05-30 14:05
result of some offline discussion: the triangle crop on the left side of [the last batch](https://github.com/researchstudio-sat/webofneeds/issues/1720#issuecomment-393168356) should be a bit bigger, as should the other triangles. If that size isn't a variable yet, I'll change it into one and slightly increase it.

No.3 would require switching to drop-shadows throughout the design and might be a bit too much work for now as we need to define which view changes in what way. I can open an issue. :)

**Comment by m0ru** [comment] 2018-05-30 14:06
Or we could add a small pic/part of the own need there :)

**Comment by m0ru** [comment] 2018-05-30 14:07
I'll sketch something :)

**Comment by quasarchimaere** [comment] 2018-05-30 14:08
not sure if this is the case in of an open received request but i agree, maybe we can ignore this indifference

**Comment by m0ru** [comment] 2018-05-30 14:13
incoming requests look different:

![image](https://user-images.githubusercontent.com/1730492/40725713-636430cc-6424-11e8-89e7-52d479532960.png)

**Comment by m0ru** [comment] 2018-05-30 14:16
matches look similar tho:

![image](https://user-images.githubusercontent.com/1730492/40725867-c948a364-6424-11e8-8605-06ccc18f130b.png)


![image](https://user-images.githubusercontent.com/1730492/40725848-bdfbc70c-6424-11e8-9e40-5fd1b6c2a2fc.png)

**Comment by m0ru** [comment] 2018-05-30 14:18
we could change the matches, so the other side's post info looks like it's the first chat message or something like that :)
(i.e. have the normal chat-frame)

**Closed** 2018-06-06 14:29 UTC
Labels: testing
