### ISSUE TITLE
needs receive empty '?'-hints

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#954] opened 2017-01-30 11:00 UTC
![grafik](https://cloud.githubusercontent.com/assets/7766279/22420677/dd5e88b0-e6e3-11e6-9149-c5f67a76f910.png)

need url: https://node.matchat.org/won/page/need/2678936896316461000

**Comment by fkleedorfer** [comment] 2017-01-30 11:05
I just wanted to post this issue too. 

Steps to reproduce: use one account to create two needs that are matchable with each other. Wait for matches.

I don't think that it's a match with itself, because there is no such connection in the connection container, though. It might be that filtering out a user's other needs from the matches has stopped working perfectly, and we get to see the effects: A match with something without a title, URI, image, etc.

**Comment by heikofriedrich** [comment] 2017-01-30 11:07
the match is actually with another need, you can see this in the rdf remote need: https://node.matchat.org/won/page/connection/ru8zdld7hvx52dkh6crl
it is somehow mixed in the owner then?

**Comment by fkleedorfer** [comment] 2017-01-30 11:27
Changed the title from describing a suspected cause to describing a perceived error

**Comment by quasarchimaere** [comment] 2017-01-31 09:16
marked as prio:high this issue also occured to me as well

**Comment by m0ru** [comment] 2017-02-01 13:12
i can't reproduce it on matchat.org. i'll try with a matcher on localhost.

**Comment by m0ru** [comment] 2017-02-01 13:59
can't reproduce it locally either

**Comment by m0ru** [comment] 2017-02-01 15:00
Caused by #942, as sometimes own needs aren't loaded and thus matches with own needs not properly filtered out.

**Closed** 2017-02-07 16:40 UTC
Labels: bug, ready, UX
