### ISSUE TITLE
 need-titles ending in  `&nbsp;` / `<br>` - contenteditable strikes again

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1080] opened 2017-05-15 11:41 UTC
sometimes need-titles still end in `&nbsp;` or `<br>`, due to problems with mediumjs / contenteditable.

Related to #1042

**Comment by fkleedorfer** [comment] 2017-05-15 12:01
duplicate of #1052

**Closed** 2017-05-15 16:20 UTC
Labels: bug, testing
