### ISSUE TITLE
Archived Need view breaks when opening

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#2765] opened 2019-02-22 11:17 UTC
![grafik](https://user-images.githubusercontent.com/32457902/53239201-b40b9700-369b-11e9-9a4e-c9c2f8efaff2.png)

![grafik](https://user-images.githubusercontent.com/32457902/53239184-a6561180-369b-11e9-932a-5cc9fa47f780.png)

![grafik](https://user-images.githubusercontent.com/32457902/53239224-c4237680-369b-11e9-9243-aab160cfdfa7.png)

Occured on live (22.02.19)

**Comment by quasarchimaere** [comment] 2019-02-22 11:28
pretty sure pr #2762 would fix this

**Comment by quasarchimaere** [comment] 2019-02-22 14:01
nvm the issue is not fixed within that pr...

**Closed** 2019-02-25 07:15 UTC
Labels: testing
