### ISSUE TITLE
Sending Requests (or possibly changing the connectionstate at all) is not propagated correctly to the client

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1996] opened 2018-06-21 13:54 UTC
i just found out that our archiving unarchiving issue #1891 is also present for connections... just send a request to a need (from a non whatsaround need) and reload the page afterwards (or login again) you will find that the connection will stil show up as a suggested conn, but if you look into the rdf of the connection you see that the state is saved correctly on the server

this seems to be a caching issue
related to #1891 we should fix both in one sitting

i think this issue intensifies the magnitude of the problem, because it is worse to not see the correct connectionstate compared to the wrong needstate

**Comment by quasarchimaere** [comment] 2018-06-21 13:57
imho we should tackle this and #1891 because it is really rather annoying and a severe issue

**Comment by peacememories** [comment] 2018-06-29 16:04
Should we close this as a "duplicate" and add relevant information to #1891 since it seems to be caused by the same caching issue?

**Closed** 2018-07-03 16:55 UTC
Labels: bug, testing
