### ISSUE TITLE
Back-Button in post-view not always leading back

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1096] opened 2017-05-18 14:18 UTC
Currently it always leads to the post-overview, even when people started out in the feed view.

**Comment by heikofriedrich** [comment] 2017-08-21 08:55
this is quite irritating, happens to me in firefox

**Comment by heikofriedrich** [comment] 2017-08-30 09:23
I think this happens when you follow a HTML link to matchat. then the back-button doesnt work anymore. this happens on our git hub page where a lin to matchat is: https://github.com/researchstudio-sat/webofneeds. i also tested with another html document with a link to matchat. same happens there!

**Comment by quasarchimaere** [comment] 2017-11-21 08:54
is duplicate of #1312

**Closed by quasarchimaere** 2017-11-21 08:54 UTC
Labels: duplicate
