### ISSUE TITLE
Matches are not shown in postbox overview

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#255] opened 2015-02-25 14:51 UTC
Postbox overview (number of matches = 0):
![image](https://cloud.githubusercontent.com/assets/7766279/6372626/e166e74a-bd05-11e4-94df-f5427b226043.png)

Need details view and matches (number of matches = 4):
![image](https://cloud.githubusercontent.com/assets/7766279/6372665/14d203ee-bd06-11e4-92d9-4dedc7ee1244.png)

**Comment by sbyim** [comment] 2015-02-26 10:12
can't reproduce this one.
the postbox notification only shows the count of "new" matches.
a match is considered as new, if the user hasn't clicked on the match connection(the four matches in the second screenshot)

**Comment by heikofriedrich** [comment] 2015-02-26 12:35
ahhh ok i didnt look sharp enogh to see that only unread matches ae shown ...

**Comment by sbyim** [comment] 2015-02-26 13:08
closing.

**Closed by sbyim** 2015-02-26 13:08 UTC
Labels: bug
