### ISSUE TITLE
Type error: e is undefined when showing matches

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#963] opened 2017-02-02 11:29 UTC
Quite severe because it breaks the GUI.

message: 
```
Error: e is undefined
selectFromState/receivedHintEvents<@https://www.matchat.org/owner/generated/app_jspm.bundle.js:28360:25
[...]
```
Code there: 
```
 OverviewPostsController = function OverviewPostsController() {
                _classCallCheck(this, OverviewPostsController);

                attach(this, serviceDependencies, arguments);
                this.selection = 1;
                window.ovp4dbg = this;

                var selectFromState = function selectFromState(state) {
                    var unreadEvents = selectUnreadEvents(state);
                    var receivedHintEvents = unreadEvents.filter(function (e) {
                        return e.get('eventType') === won.EVENT.HINT_RECEIVED;
                    });
                    var unseenMatchesCounts = Immutable.Map();
                    receivedHintEvents.forEach(function (e) {
                        var receiverNeed = e.get('hasReceiverNeed');
                        var count = unseenMatchesCounts.get(receiverNeed);
                        if (!count) {
                            unseenMatchesCounts = unseenMatchesCounts.set(receiverNeed, 1);
                        } else {
                            unseenMatchesCounts = unseenMatchesCounts.set(receiverNeed, count + 1);
                        }
                    });

                    //won.EVENT.HINT_RECEIVED -> matches
                    //won.EVENT.WON_MESSAGE_RECEIVED -> convoMessages (!= convos with new messages <- we want this)
                    //won.EVENT.CONNECT_RECEIVED -> incomingRequests

                    //goal: unseenCounts = { <uri> : { matches: 11, conversations: 0, incomingRequests: 2 }, <uri>:...}
                    //TODO use memoized selector to avoid running this calculation on every tick

                    var ownNeeds = selectOwnNeeds(state);
                    var activePosts = ownNeeds.filter(function (post) {
                        return post.getIn(['won:isInState', '@id']) === won.WON.ActiveCompacted;
                    });
                    activePosts = activePosts ? activePosts.toArray() : [];

                    var inactivePosts = ownNeeds.filter(function (post) {
                        return post.getIn(['won:isInState', '@id']) === won.WON.InactiveCompacted;
                    });
                    inactivePosts = inactivePosts ? inactivePosts.toArray() : [];

                    return {
                        activePostsUris: activePosts.map(function (p) {
                            return p.get('@id');
                        }),
                        activePostsCount: activePosts.length,
                        inactivePostsUris: inactivePosts.map(function (p) {
                            return p.get('@id');
                        }),
                        inactivePostsCount: inactivePosts.length,
                        unreadEvents: unreadEvents,
                        unreadCounts: selectUnreadCountsByNeedAndType(state),
                        //unreadMatchEventsOfNeed: unseenMatchesCounts,
                        //nrOfPostsWithNotifications: unseenMatchesCounts.length
                        drafts: null,
                        activePostsOpen: state.getIn(["postOverview", "activePostsView"]),
                        draftsOpen: false,
                        closedPostsOpen: state.getIn(["postOverview", "closedPostsView"])
                    };
                };

                var disconnect = this.$ngRedux.connect(selectFromState, actionCreators)(this);
                this.$scope.$on('$destroy', disconnect);
            };

            OverviewPostsController.$inject = [];

```

**Comment by quasarchimaere** [comment] 2017-02-02 12:55
should also be a duplicate of something that has been fixed in "partial fix" pull request already

**Closed** 2017-03-20 17:45 UTC
Labels: bug, testing
