### ISSUE TITLE
Need is Lost after publish due to an Unhandled exception when publishing with faulty details

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#1825] opened 2018-05-25 08:49 UTC
Creating a new post with faulty TTL entered as a detail results in an unhandled promise rejection error. Console output: 
```
es6.promise.js:110 Unhandled promise rejection Error: error while parsing the following turtle:

@prefix webID: <http://www.example.com/webids/>.
@prefix msg: <http://purl.org/webofneeds/message#>.
@prefix dc: <http://purl.org/dc/elements/1.1/>.
@prefix agr: <http://purl.org/webofneeds/agreement#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix won: <http://purl.org/webofneeds/model#>.
@prefix gr: <http://purl.org/goodrelations/v1#>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix rdfg: <http://www.w3.org/2004/03/trix/rdfg-1/>.

something wrong

----

Unexpected "something" on line 14.
    at l._syntaxError (N3Lexer.js:363)
    at m (N3Lexer.js:330)
    at l._tokenizeToEnd (N3Lexer.js:315)
    at N3Lexer.js:386
    at e.exports (_invoke.js:5)
    at m.(/owner/anonymous function) (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:83:41376)
    at Number.y (_task.js:21)
    at MessagePort._ (_task.js:25)
```

From a user perspective, the post just disappears after clicking publish.

**Comment by quasarchimaere** [comment] 2018-08-24 07:48
may be the cause of the subjective "post creation takes too long issue" #2274 (which has been closed since)

**Comment by quasarchimaere** [comment] 2018-11-14 10:36
Closing this issue since ttl creation is currently not implemented/accessible

**Closed by quasarchimaere** 2018-11-14 10:36 UTC
Labels: bug, later
