### ISSUE TITLE
Matches of closed need

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#246] opened 2015-02-16 11:46 UTC
1. Suggested connections are not closed when the post is closed. Is it intended?
2. How the closed needs should be handled on the other side? I.e. I have need A active, the matched need B, also active, is sent for my need A, then the owner of need B deactivates it. From the user point of view, I would like to see that the need B is closed, so that I don't bother connecting to it...

**Comment by sbyim** [comment] 2015-02-16 12:39
> Suggested connections are not closed when the post is closed. Is it intended?

is mentioned here. #113
currently a need deactivation call on Won node closes also all of its connections(including matches).
but it is not clear how to implement this.
Currently matches are not displayed as closed, because we have to change the close method of OwnerProtocolOwnerServiceImpl or eventually implement the interface in order to send close events caused by need deactivation to the client

**Comment by sbyim** [comment] 2015-02-18 11:59
update.. matches are not being closed at the moment. we have to decide if we want to close the match connections too.

**Comment by fkleedorfer** [comment] 2016-05-30 17:00
connected to #579

**Comment by quasarchimaere** [comment] 2017-10-03 10:53
since #579 is already merged and tested ok, this issue is fixed as well -> close

**Closed by quasarchimaere** 2017-10-03 10:53 UTC
Labels: design decision, question
