### ISSUE TITLE
Owner app is hanging in "Publishing ..." state after need creation if wonnode doesnt answer

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#635] opened 2016-06-20 07:46 UTC
Example: there is a certificate check in the wonnode going wrong with the message:

"INFO  w.c.a.CertificateCheckingBrokerFilter - denying message consumption to owner as public key hash does not equal owner id" 

and owner just keeps waiting for response.

**Comment by fkleedorfer** [comment] 2016-06-20 08:32
In this case, the behaviour of the GUI is due to changes in the way queue names are constructed from client certificates. This currently can only be fixed by emptying the ownerapplications table.

**Comment by fkleedorfer** [comment] 2016-06-20 08:40
However, in general, this issue means that the owner application should be more resilient with respect to problems connecting to nodes. In the current case, the owner application cannot regster with the node, and the problem is permanent, but solvable with human intervention. In a similar, but different situation, the problem may be transient (e.g., a temporary network problem), or permanent and unsolvable.

Ideally, the owner can find out which kind of failure it is facing and behave accordingly

**Comment by fkleedorfer** [comment] 2018-06-01 08:57
Cleaning up old issues. This one points to a larger owner webapp admin feature, which is out of scope right now.

**Closed by fkleedorfer** 2018-06-01 08:57 UTC
Labels: bug
