### ISSUE TITLE
skinning: close post icon still red

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1416] opened 2018-02-06 11:43 UTC
e.g. uki:

![close.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5714a67d0019b11300f6d9bf/125516c66e82c728ace21e0d46eb98953087c1e5cdf9ad4cae58f3806b1c65267e54a17e71d6e77abc1a7d560d0d4eac415e5d40faab8e39baa47e21d40854b088270a36d43703adb1881eba00bd298a4881b7bc824ec7fa70.png)

**Comment by sigpie** [comment] 2018-04-04 12:38
Duplicate of #1423

**Closed** 2018-04-06 13:29 UTC
