### ISSUE TITLE
Automatic What's New Posting

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1653] opened 2018-04-25 12:12 UTC
Whenever the owner webapp is opened, and there is no active session (and no remember-me cookie), an anonymous user should be created.
Next, a "What's New" - posting should be created, which is a What's Around without a location.
if any "What's New" or "What's Around" already exist in that situation, they should be closed

**Comment by quasarchimaere** [comment] 2018-04-26 12:57
also see feature #1632

**Comment by m0ru** [comment] 2018-05-09 16:51
Asking for a users location straight away comes off somewhat creepy. We should find a way to pass some text along (e.g. by showing a custom popup/-over) or keep this user-initiated but make it a single click and visually the first thing they'll look a (+explanation of the value it brings).

**Comment by maxstolze** [comment] 2018-05-30 08:27
Duplicate of #1632

**Closed** 2018-05-30 15:05 UTC
Labels: User Story, testing
